name: lint-flake8

on: push

jobs:
  lint-job:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
      - run: |
          pip install poetry
          make install
      - name: Test with flake8
        run: make lint
